version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:${PSQL_V}-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_U}
      - POSTGRES_PASSWORD=${PSQL_PASS}
    ports:
      - ${PSQL_PORT}:5432
    restart: always

  web:
    container_name: cs-50_commerce
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - ${PORT}:8000
    environment:
      - POSTGRES_NAME=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_U}
      - POSTGRES_PASSWORD=${PSQL_PASS}
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db-data: